# Generated by Django 3.2.12 on 2023-11-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeleave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeLeave',
            new_name='EmployeeLeave',
        ),
    ]
